package com.vitor.calculadora.utils;

public interface Const {
    String SOMA = "SOMA";
    String SUBTRACAO = "SUBTRACAO";
    String MULTIPLICACAO = "MULTIPLICACAO";
    String DIVISAO = "DIVISAO";
    String RESTO_DIVISAO = "RESTO_DIVISAO";
    String LISTA_RESULTADOS = "LISTA_RESULTADOS";
    String LISTA_OPERACOES = "LISTA_OPERACOES";
    String PRIMEIRO_NUMERO_OPERACAO = "PRIMEIRO_NUMERO_OPERACAO";
    String SEGUNDO_NUMERO_OPERACAO = "SEGUNDO_NUMERO_OPERACAO";
    String OPERACAO = "OPERACAO";
    String RETORNO_POSICAO = "RETORNO_POSICAO";
    String REGEX_OPERACOES = "[0-9.]+";
    String REGEX_NUMEROS_OPERACAO = "[-*%\\/+]";
    String REGEX_WHITESPACES = "\\s";
    int ABRE_HISTORICO = 1;
}
